[package]
name = "myraytracing"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.14.0"
image = "0.25.9"
indicatif = { version = "0.18.3", features = ["rayon"] }
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.10"
